### ISSUE TITLE
Separate bucket needed for every project?

### ISSUE THREAD

**Issue by kennu** [serverless/serverless-meta-sync#6]
Looking at the S3 key structure, it seems that variables are stored as:

```
BUCKET/_servereless_meta_sync/variables/s-variables-development.json
```

Does it mean I need to create a separate bucket for every project to be synced?

**Comment by kennu** [comment]
Perhaps the key prefix could be made configurable in s-project.json. Especially since it has a typo :-)

**Comment by minibikini** [comment]
Done. Thank you @kennu!

**Comment by edclement** [comment]
can you cut a 0.0.2 for this?

**Comment by kennu** [comment]
Works very nicely, thanks. :-)
